# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da30c720c48b2e356d21bb3643a0b1c4c63c294c2bf422f42308810ac5a14cc376cd1c1ff2c22aee6946e70576b847f5e2706077abcd566f6de89a153d0b521

test:
  secret_key_base: bd2ef6ae7a303e9bbb3e53d7140d2e185d560816a5ee7f6fd99631ed5c6282e0fc1fb2f9bf4a758c6dbb226c1c5fe7f3bd40a18048a5b7fc1e59ecb73aebb172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
